define([], function() {
    return {
        "PropertyPaneDescription": "Use the settings panel to configure your table of contents.",
        "BasicGroupName": "Web Part Settings",
        "htmlTag": "Textstyle used to generate TOC",
        "textStyleHeading1Text": "Heading 1",
        "textStyleHeading2Text": "Heading 2",
        "textStyleHeading3Text": "Heading 3",
        "showTOCHeading": "Show title",
        "headingText": "Title",
        "headingTextDefaultValue": "Table of contents",
        "backToTopGroupName": "Textual settings",
        "showBackToTop": "Show back to top in paragraph",
        "backToTopText": "Label 'Back to top'",
        "backToTopDefaultValue": "Back to top",
        "backToTopFieldDescription": "Text in this field will be added to the text web part underneath each paragraph.",
        "showBackToPreviousPage": "Show back to previous page",
        "backToPreviousText": "Label 'Back to previous page'",
        "backToPreviousDefaultValue": "Back to previous page",
        "backToPreviousFieldDescription": "Text to display on the link 'Back to previous page'. This link is always the last item in the table of contents.",
        "pageInEditMode": "Page is in edit mode, table of contents is generated when you save the page.",
        "floatTOC": "Pin 'Table of Contents' to current position",
        "iconDescription": "Icons can be found in the Fabric UI style library @Microsoft. Search for 'fabric ui icons'...",
        "iconGroup": "Icons & Coloring",
        "iconTOCItem": "Icon for TOC item",
        "iconPreviousPage": "Icon for 'Previous page'",
        "tocBackgroundColor": "Backgroundcolor",
        "tocBackgroundColorDescription": "Set the background color for the table of contents, you can use any HTML color code.",
        "pinGroup": "Pinning",
        "copyGroup": "Copy settings",
        "buttonCopySettingsLabel": "Export settings",
        "buttonPasteSettingsLabel": "Import settings",
        "sampleItemLabel": "Sample item",
        "errorFieldCannotBeEmpty": "This field cannot be empty. Fill in a value!",
        "errorToggleFieldEmpty": "This field cannot be empty, if you do no want to use this field, toggle it off!"
    }
});