define([], function() {
    return {
        "PropertyPaneDescription": "Gebruik onderstaande instellingen om de inhoudsopgave te configureren.",
        "BasicGroupName": "Web part instellingen",
        "htmlTag": "Tekststijl voor het genereren van de inhoudsopgave",
        "textStyleHeading1Text": "Kop 1",
        "textStyleHeading2Text": "Kop 2",
        "textStyleHeading3Text": "Kop 3",
        "showTOCHeading": "Toon titel",
        "headingText": "Titel",
        "headingTextDefaultValue": "Inhoudsopgave",
        "backToTopGroupName": "Tekstuele instellingen",
        "showBackToTop": "Toon 'Terug naar boven' onder de paragraph",
        "backToTopText": "Label 'Terug naar boven'",
        "backToTopDefaultValue": "Terug naar boven",
        "backToTopFieldDescription": "Deze tekst wordt automatisch toegevoegd in de tekst van het web part.",
        "showBackToPreviousPage": "Toon 'Terug naar vorige pagina'",
        "backToPreviousText": "Label 'Terug naar vorige pagina'",
        "backToPreviousDefaultValue": "Terug naar vorige pagina",
        "backToPreviousFieldDescription": "Tekst die wordt getoond op de link 'Terug naar vorige pagina'. Dit item wordt als laatste toegeveoegd in de inhoudsopgave.",
        "pageInEditMode": "Pagina is in 'Bewerk modus'. Inhoudsopgave wordt alleen automatisch gemaakt in 'Lees modus'. Hieronder worden een aantal voorbeeld items getoond.",
        "floatTOC": "Pin inhoudsopgave vast op huidige positie",
        "iconDescription": "Iconen zijn te vinden in 'Fabric UI style library @Microsoft'. Zoek op 'fabric ui icons'...",
        "iconGroup": "Iconen en achtergrond",
        "iconTOCItem": "Icoon voor inhoudsopgave item",
        "iconPreviousPage": "Icoon voor 'Terug naar vorige pagina'",
        "tocBackgroundColor": "Achtergrondkleur",
        "tocBackgroundColorDescription": "Zet de achtergrondkleur van de inhoudsopgave. Je kan elke HTML kleurcode gebruiken.",
        "pinGroup": "Vastpinnen",
        "copyGroup": "Kopieer instellingen",
        "buttonCopySettingsLabel": "Exporteer instellingen",
        "buttonPasteSettingsLabel": "Importeer instellingen",
        "sampleItemLabel": "Voorbeeld item",
        "errorFieldCannotBeEmpty": "Dit veld kan niet leeg zijn, vul een waarde in!",
        "errorToggleFieldEmpty": "Dit veld kan niet leeg zijn, wanneer je het veld niet wilt zien, gebruik dan de toggle!"
    }
});